export const registro03 = {
    titulo: "Mensagem Corrompida & A Partida para Murfy",
    conteudo: [
        "Narração:",
        "Após algumas horas de estudo, seu bracelete vibrou novamente. Uma notificação do grupo Amizades do Barulho.",
        "",
        "Piloto (exausto):",
        "“Uma hora dessas fazendo chamda de vídeo no grupo kkk, Zack o que você quer...”",
        "",
        "Zack (voz animada):",
        "“Ei, RS! Parou de estudar por um segundo? já são 22:30 cara, vem pro bar central! O Dave tá apostando com todo mundo que você instalou algo novo na nave.”",
        "",
        "Piloto (sem energia):",
        "“Bom, vai ser surpresa kkk, se diverte ai.”",
        "“agora só preciso de silêncio... não de mais diversão.”",
        "",
        "[Som de canal encerrando. Breve silêncio. Apenas o som leve do ar sendo filtrado.]",
        "Narração:",
        "Ele se recostou na cadeira. Pensava em ignorar tudo, talvez até dormir, mas então... seu bracelete brilhou novamente, exibindo uma mensagem corrompida.",
        "",
        "[Som de interferência eletromagnética — chiados e falhas de áudio.]",
        "Mensagem corrompida (voz distorcida, fragmentada):",
        "“...–4817... Ba ... Murfy... longe... Zeni...ty exter... bordas... 12... não conf... na Orde... Procure Verrin Kane...”",
        "",
        "[Som de estática cortando abruptamente. Silêncio.]",
        "Piloto (confuso):",
        "“Murfy...? Isso não está nos canais oficiais, esses números parecem coordenadas... e quem diabos é Verrin Kane?”",
        "",
        "Narração:",
        "Murfy. Um nome apagado dos mapas estelares, esquecido até pelos navegadores automáticos. Era dito que ali só restavam ecos — veteranos e desertores de guerra.",
        "",
        "Piloto (voz firme):",
        "“Uma mensagem corrompida, sem registro de envio, sem destinatário... nomes desconhecidos... intrigante. Já sei pra onde vou agora.”",
        "",
        "Narração (imersiva):",
        "O piloto, intrigado, sente o impulso de partir imediatamente. O relógio marcava o fim do ciclo local — e a estação anunciava o fechamento.",
        "",
        "[Som de chiado do rádio, voz metálica e distante.]",
        "‘Atenção tripulações — último embarque autorizado às 23:00. A estação de lançamento Zenity-03 será selada em quinze minutos.’",
        "",
        "[Som de passos apressados, botas metálicas batendo no corredor.]",
        "Narração:",
        "Sem pensar duas vezes, ele corre pelos corredores cromados da estação, desviando de drones e oficiais da Ordem.",
        "",
        "[Som de respiração ofegante, portas automáticas abrindo em sequência.]",
        "Piloto (voz acelerada): “Seja o que for... preciso ver com meus próprios olhos.”",
        "",
        "[Som de despressurização leve — a escotilha da nave se abre.]",
        "Narração:",
        "Com sorte, ele chega a tempo. Os painéis reacendem, o sistema reconhece sua presença.",
        "",
        "Rádio da Estação (robótico):",
        "‘Atenção tripulações — fechamento do setor de lançamento em 20 minutos padrão. Todas as saídas deverão ser registradas até 22:50.’",
        "",
        "[Painel liga com um zumbido suave.]",
        "Voz do Sistema:",
        "‘Bem-vindo de volta, piloto RS-07. Registre seu destino antes da partida. A nave permanecerá bloqueada até a confirmação.’",
        "",
        "Piloto (rápido):",
        "‘Destino... Murfy.’",
        "",
        "Voz do Sistema:",
        "‘Destino não reconhecido. Autorização recusada.’",
        "",
        "Piloto (pensando):",
        "“Se eu for pedir permissão, vão me segurar até amanhã...”",
        "“Tá certo. Vamos fazer do jeito antigo. Desculpa Dave, mas vou fazer um upgrade.”",
        "",
        "Narração:",
        "O piloto abre o painel de navegação e manuseia os fios, tentando mudar as configurações de segurança.",
        "Faíscas saltam, o cheiro de ozônio toma o cockpit, e uma interface antiga pisca por um instante—até se apagar por completo.",
        "Ele reconecta os cabos improvisados com o painel e tenta novamente.",
        "",
        "Voz do Sistema (confusa):",
        "Controle manual indisponível. Motor primário: INOPERANTE. Configuração incorreta no painel!",
        "",
        "Piloto:",
        "É claro... eu esculhambei o painel.",
        "",
        "Narração:",
        "Ele respira fundo.",
        "Olha para a mochila jogada no canto da nave.",
        "E lembra.",
        "",
        "Piloto:",
        "Pera… o condensador alternativo. Aquele que eu trouxe ‘pra emergências’…",
        "",
        "Narração:",
        "Ele pega a pequena peça cilíndrica — improvisada, remendada, e totalmente reprovada por Dave — e a encaixa no soquete exposto do motor.",
        "O sistema chia, luzes piscam, e por um segundo parece que tudo vai explodir.",
        "Então… estabiliza.",
        "",
        "Voz do Sistema (confusa):",
        "‘Componente não homologado detectado… Canal de comunicação temporário estabelecido. Controle manual ativada.’",
        "",
        "Piloto:",
        "‘Agora sim... Destino manual — Murfy, setor limitrôfe. Coordenadas aproximadas... X:-4817.00, Y:1200.00, Z:????.??.’",
        "",
        "[Painel confirma com um bip grave.]",
        "Voz do Sistema:",
        "‘Rota manual registrada. Partida sob risco do piloto. Deseja continuar?’",
        "",
        "Piloto:",
        "“22:58... se eu esperar, fico preso aqui. Confirmar.”",
        "",
        "[Som dos motores reacendendo, estrutura vibrando.]",
        "Voz do Sistema (último aviso):",
        "‘Decolagem não supervisionada detectada. Que a sorte acompanhe seu trajeto, RS-07.’",
        "",
        "Narração:",
        "A nave treme, o hangar se enche de luz e Zenity vira apenas um reflexo distante. O piloto parte — rumo às bordas.",
        "Sem ordens. Sem relatórios.",
        "Apenas um chamado...",
        "",
        "[Som ambiente: vento espacial abafado, motores desacelerando, travas metálicas libertando.]",
    ],
};