export const registro01 = {
  titulo: "A Licença e o Retorno a Zenity — Versão Narrada",
  conteudo: [
    "[Som ambiente: vibração metálica suave, o zumbido constante dos propulsores.]",
    "",
    "Narração:",
    "A nave viaja em velocidade de cruzeiro, atravessando o vazio do sistema.",
    "O piloto observa as estrelas pela janela e respira fundo imaginando como seria ver o pôr do sol em Zenity.",
    "",
    "Piloto (voz cansada):",
    "\"Três meses... sem pousar nem pra ver um pôr do sol. Acho que já é hora de parar um pouco.\"",
    "",
    "[Som de painel abrindo, interface holográfica piscando.]",
    "",
    "Voz do Sistema:",
    "\"Solicitações de licença disponíveis até 18:00, horário padrão Zenity. Deseja prosseguir?\"",
    "",
    "Piloto:",
    "\"Sim. Solicitar licença por... cinco dias.\"",
    "",
    "[Som de digitação digital e envio de requisição.]",
    "",
    "Narração:",
    "A mensagem foi clara, simples —",
    "\"Solicitação de pausa temporária para estudo e recondicionamento físico.\"",
    "",
    "[Pequeno silêncio. Sons de nave em modo autônomo.]",
    "",
    "Voz do Sistema:",
    "\"Solicitação analisada. Autorizados três dias de licença. Retorno obrigatório para avaliação de saúde.\"",
    "",
    "Piloto (irônico, rindo de leve):",
    "\"Três dias... generosos como sempre.\"",
    "",
    "[Som de motores ajustando rota. Nave reduzindo velocidade.]",
    "",
    "Narração:",
    "Ele ajusta o curso e segue para Zenity, o centro da nova Ordem.",
    "Um planeta luminoso, prateado, frio — feito pra parecer pacífico.",
    "",
    "[Som de comunicação chegando — bip rápido.]",
    "",
    "Voz automatizada:",
    "\"Mensagem recebida da Organização Estelar: Preparação antecipada — Expedição Setor Havoc em avaliação.\"",
    "",
    "Piloto (sério):",
    "\"Nem desci e já tem outra missão... Setor Havoc, é? Faz séculos que ninguém vai pra lá.\"",
    "\"Se não me engano, existem muitas histórias sobre esse setor...\"",
    "",
    "[Som ambiente: vento suave e ecos metálicos da plataforma de atracagem. Passos sobre metal e vozes distantes ecoando pela estação.]",
    "",
    "Narração:",
    "Já fazia um bom tempo desde a última vez que ele voltara a Zenity.",
    "A cidade orbital parecia diferente — mais limpa, mais silenciosa... e, de alguma forma, menos viva.",
    "As velhas torres reluziam em tons de prata e azul, projetando o símbolo da Ordem nos céus —",
    "um lembrete constante de quem dominava o espaço.",
    "",
    "[Som de passos, painel de controle abrindo.]",
    "",
    "Piloto (para o sistema local):",
    "\"Controle Zenity, aqui é o piloto código RS-07 em licença temporária.",
    "Acabei de retornar do setor Sigma em missão. Solicito autorização para doca de curta permanência.\"",
    "",
    "Voz do Controle:",
    "\"Autorizado, RS-07. Bem-vindo de volta a Zenity.",
    "Relembramos que áreas centrais estão sob vigilância. Tenha um bom descanso.\"",
    "",
    "Narração:",
    "Ele apenas assentiu. Descanso... palavra bonita pra algo que nunca vinha de verdade.",
  ],
};