export const registro03 = {
    titulo: "Mensagem Corrompida & A Partida para Murfy",
    conteudo: [
        "[Som distante de notificações de colegas — risadas e vozes pelo comunicador.]",
        "Colega (voz animada):",
        "“Ei, RS! Parou de estudar por um segundo? Vem pro bar central! A folga é curta, mas ainda dá pra uma rodada.”",
        "",
        "Piloto (sem energia):",
        "“Valeu galera, mas não hoje. Preciso de silêncio... não de mais ruído.”",
        "",
        "[Som de canal encerrando. Breve silêncio. Apenas o som leve do ar sendo filtrado.]",
        "Narração:",
        "Ele se recostou na cadeira. Pensava em ignorar tudo, talvez até dormir, mas então... seu bracelete brilhou novamente, exibindo uma mensagem corrompida.",
        "",
        "[Som de interferência eletromagnética — chiados e falhas de áudio.]",
        "Mensagem corrompida (voz distorcida, fragmentada):",
        "“...–4817... Ba ... Murfy... longe... Zeni...ty exter... bordas... 12... não conf... na Orde... Procure Verrin Kane...”",
        "",
        "[Som de estática cortando abruptamente. Silêncio.]",
        "Piloto (confuso):",
        "“Murfy...? Isso não está nos canais oficiais, esses números parecem coordenadas... e quem diabos é Verrin Kane?”",
        "",
        "Narração:",
        "Murfy. Um nome apagado dos mapas estelares, esquecido até pelos navegadores automáticos. Era dito que ali só restavam ecos — veteranos e desertores de guerra.",
        "",
        "Piloto (voz firme):",
        "“Uma mensagem corrompida, sem registro de envio, sem destinatário... nomes desconhecidos... intrigante. Já sei pra onde vou agora.”",
        "",
        "Narração (imersiva):",
        "O piloto, intrigado, sente o impulso de partir imediatamente. O relógio marcava o fim do ciclo local — e a estação anunciava o fechamento.",
        "",
        "[Som de chiado do rádio, voz metálica e distante.]",
        "‘Atenção tripulações — último embarque autorizado às 23:00. A estação de lançamento Zenity-03 será selada em quinze minutos.’",
        "",
        "[Som de passos apressados, botas metálicas batendo no corredor.]",
        "Narração:",
        "Sem pensar duas vezes, ele corre pelos corredores cromados da estação, desviando de drones e oficiais da Ordem.",
        "",
        "[Som de respiração ofegante, portas automáticas abrindo em sequência.]",
        "Piloto (voz acelerada): “Seja o que for... preciso ver com meus próprios olhos.”",
        "",
        "[Som de despressurização leve — a escotilha da nave se abre.]",
        "Narração:",
        "Com sorte, ele chega a tempo. Os painéis reacendem, o sistema reconhece sua presença.",
        "",
        "Rádio da Estação (robótico):",
        "‘Atenção tripulações — fechamento do setor de lançamento em vinte minutos padrão. Todas as saídas deverão ser registradas até 22:50.’",
        "",
        "[Painel liga com um zumbido suave.]",
        "Voz do Sistema:",
        "‘Bem-vindo de volta, piloto RS-07. Registre seu destino antes da partida. A nave permanecerá bloqueada até a confirmação.’",
        "",
        "Piloto (rápido):",
        "‘Destino... Murfy.’",
        "",
        "Voz do Sistema:",
        "‘Destino não reconhecido. Autorização recusada.’",
        "",
        "Piloto (pensando):",
        "“Se eu for pedir permissão, vão me segurar até amanhã...”",
        "“Tá certo. Vamos fazer do jeito antigo.”",
        "",
        "Narração:",
        "Ele aciona um módulo oculto — clique mecânico. Um brilho azul percorre o console.",
        "",
        "Voz do Sistema (confusa):",
        "‘Canal de comunicação temporário detectado. Rota manual ativada.’",
        "",
        "Piloto:",
        "‘Agora sim... Destino manual — Murfy, setor limitrôfe. Coordenadas aproximadas... X:-4817.00, Y:1200.00, Z:????.??.’",
        "",
        "[Painel confirma com um bip grave.]",
        "Voz do Sistema:",
        "‘Rota manual registrada. Partida sob risco do piloto. Deseja continuar?’",
        "",
        "Piloto:",
        "“22:43... se eu esperar, fico preso aqui. Confirmar.”",
        "",
        "[Som dos motores reacendendo, estrutura vibrando.]",
        "Voz do Sistema (último aviso):",
        "‘Decolagem não supervisionada detectada. Que a sorte acompanhe seu trajeto, RS-07.’",
        "",
        "Narração:",
        "A nave treme, o hangar se enche de luz e Zenity vira apenas um reflexo distante. O piloto parte — rumo às bordas.",
        "Sem ordens. Sem relatórios.",
        "Apenas um chamado...",
        "",
        "[Som ambiente: vento espacial abafado, motores desacelerando, travas metálicas libertando.]",
    ],
};