export const registro05 = {
    titulo: "O Bar Murfy — O Velho",
    conteudo: [
        "Narrador:",
        "A porta range ao abrir. O som distante de motores se apaga.",
        "O ar é denso — cheira a óleo, poeira e lembranças.",
        "O bar é pequeno, mal iluminado. Um jukebox quebrado emite estática.",
        "No balcão, um velho observa o vazio de um copo.",
        "A cicatriz em seu rosto brilha sob a luz vermelha piscante.",
        "Você se aproxima. O velho fala sem olhar pra você.",
        "",
        "Velho Misterioso:",
        "Heh… não costumo ver uniforme da Ordem por aqui.",
        "Veio procurar glória ou perdão?",
        "",
        "Piloto (calmo, tira o casaco):",
        "Silêncio.",
        "",
        "Velho Misterioso (ri alto, um riso seco):",
        "Hah! Silêncio!",
        "Garoto, ninguém entra num bar pedindo silêncio.",
        "Ou quer esquecer… ou quer lembrar.",
        "",
        "Piloto:",
        "Talvez um pouco dos dois.",
        "Estou buscando informações, nomes, histórias sobre...",
        "",
        "Velho Misterioso (interrompe):",
        "Histórias, é?",
        "A única coisa que vive pra sempre por aqui é a conta pendurada.",
        "",
        "Piloto:",
        "Deve ser difícil manter as histórias vivas… num lugar que já esqueceu de viver.",
        "",
        "Velho Misterioso:",
        "Garoto, se quer poesia, senta no Observatório Central.",
        "Aqui só tem bebida ruim e arrependimento barato.",
        "Mais uma! — E traz rápido, antes que eu fique lúcido.",
        "",
        "Narração:",
        "O atendente serve. O velho bebe, pesado.",
        "",
        "Piloto (baixo):",
        "Ouvi falar de um nome.",
        "Um que desapareceu dos registros da Ordem.",
        "",
        "Velho Misterioso (pausando o gole):",
        "Heh… você é ousado, garoto.",
        "Sabe quantos ainda têm coragem de dizer que a Ordem não tem registrado?",
        "Nem os mortos!",
        "",
        "Piloto:",
        "Mas o senhor deve saber de algo se eu contar… não é?",
        "",
        "Velho Misterioso:",
        "Lembrar?",
        "Ah, lembro de muita coisa...",
        "Mas a bebida tem um acordo comigo: quanto mais eu bebo, mais o passado apaga.",
        "Pena que a memória não cumpre o contrato.",
        "",
        "Narração:",
        "O piloto tira algo do bolso — um tubo metálico ‘Clearsil’.",
        "",
        "Velho Misterioso:",
        "Clearsil? Ah, claro… o brinquedinho dos pilotos limpinhos.",
        "Um sopro e pronto — mente clara, alma pura.",
        "Garoto… se isso limpasse o que eu vi, eu teria bebido um frasco inteiro por dia.",
        "",
        "Piloto:",
        "Funciona. Ao menos pra lembrar o que é real.",
        "",
        "Narração:",
        "O velho encara o tubo. Hesita. Toma um sopro.",
        "O brilho azul corre pelas veias do pescoço.",
        "",
        "Velho Misterioso (voz mais firme):",
        "…maldição. Fazia tempo que eu não sentia o mundo tão… nítido.",
        "Você devia ter deixado eu continuar tonto.",
        "A sobriedade não combina comigo.",
        "",
    ],
}; 