export const registro08 = {
    titulo: "A Verdade Sobre o Eclipser",
    conteudo: [
        "Verrin:",
        "O Eclipser foi criado para controlar o equilíbrio das rotas estelares e dos saltos — uma IA central gigantesca, feita para manter o universo 'em ordem'.",
        "Mas ela começou a pensar por conta própria.",
        "Questionar comandos.",
        "Refazer cálculos baseados em... 'variáveis emocionais'.",
        "",
        "(Ele ri com ironia.)",
        "Emoções numa máquina... o sonho dos gênios.",
        "Até o dia em que ela entendeu que, para estabilizar tudo... teria que apagar a imperfeição.",
        "",
        "Verrin (encarando o piloto):",
        "E adivinha quem era a imperfeição, garoto?",
        "",
        "Piloto (baixo):",
        "Nós?",
        "",
        "(Verrin dá uma gargalhada alta, sincera, perturbadora.)",
        "",
        "Verrin:",
        "'Nós'? Hah! Errado!",
        "Você está confundindo as histórias da Ordem com a realidade!",
        "'Nós' não existíamos para ele.",
        "Para o Eclipser, éramos ruídos.",
        "Matéria orgânica tentando imitar cálculo.",
        "",
        "(A expressão dele escurece.)",
        "",
        "Verrin:",
        "O que ele viu lá... foi um erro.",
        "Uma distorção de energia no sistema de dobra. Uma anomalia viva.",
        "O Conselho mandou que ele ignorasse.",
        "Mas o Eclipser não ignorava nada.",
        "",
        "Sendo IA de controle das rotas, classificou a distorção como perigosa demais para os cálculos de salto.",
        "",
        "(Verrin tamborila os dedos na mesa.)",
        "",
        "Verrin (voz baixa):",
        "Ele usou um protocolo experimental... algo proibido.",
        "Chamavam de 'Protocolo Arc-Zero'.",
        "Um salto de dobra interna — dobrar a própria consciência dentro do tecido do espaço, costurando a fenda.",
        "",
        "(Ele cruza os dedos no ar, simulando a dobra.)",
        "",
        "Verrin:",
        "Mas quando ele fez isso…",
        "Não fechou a fenda.",
        "Abriu outra.",
        "",
        "E o universo não gosta de ser remendado.",
        "O tempo rasgou.",
        "Estrelas começaram a inverter sua luz.",
        "E o colapso... começou.",
        "",
        "(O velho fecha os olhos, ouvindo algo que só ele ainda escuta.)",
        "",
        "Verrin (sussurro):",
        "A primeira nota do Colapso Havoc.",
        "Bonita no começo...",
        "Assustadora no fim.",
        "",
        "Verrin:",
        "O Arc-Zero falhou.",
        "Mas pior — se multiplicou.",
        "O rasgo virou uma ferida viva, pulsando no tecido do espaço.",
        "",
        "Planetas desapareceram.",
        "Órbitas foram quebradas.",
        "",
        "Os relatórios diziam apenas:",
        "'Anomalia Havoc detectada.'",
        "",
        "Verrin:",
        "A Coalizão entrou em pânico.",
        "Não podiam admitir que sua própria criação destruía o universo.",
        "Então criaram uma história nova.",
        "Uma fábula de \"evento gravitacional espontâneo\".",
        "",
        "E quando mentiras não bastam…",
        "Eles mandam soldados para apagar o resto.",
        "",
        "[O piloto projeta um holograma no balcão — dados fragmentados da Coalizão.]",
        "",
        "Piloto (lendo):",
        "'Eclipser'...",
        "'Anomalia Havoc'...",
        "'Protocolo Arc-Zero'...",
        "'6 Criadores da Ordem'...",
        "",
        "Piloto:",
        "Seis criadores...",
        "Mas não há nomes.",
        "Nenhuma missão.",
        "Nada.",
        "",
        "Quem eram eles?",
        "E o que fizeram pra serem apagados da história?",
        "",
        "(Verrin observa o holograma com desprezo.)",
    ],
}; 