export const registro13 = {
    titulo: "Contos de um Mentiroso Visionário",
    conteudo: [
        "(Transição: o som cessa. O hangar se desfaz, o bar reaparece. Verrin está de volta ao balcão, velho, exausto, com a garrafa pela metade. Por um instante, o reflexo da garrafa mostra o rosto jovem dele — depois desaparece.)",
        "",
        "Verrin (voz baixa, rouca, olhando o vazio):",
        "Rho me ejetou pra fora do tempo.",
        "Disse que alguém precisava sair...",
        "alguém que pudesse mudar o rumo da história.",
        "",
        "(Pausa. O som ambiente do bar se mistura a um eco distante — o som de vento estelar. O olhar de Verrin perde foco, e o tom de sua voz muda, como se narrasse algo que já não pertence mais a ele.)",
        "",
        "Verrin:",
        "Quando acordei...",
        "o silêncio era tudo o que restava.",
        "Flutuava num campo morto, sem sinal de vida, sem constelações conhecidas.",
        "O painel marcava coordenadas impossíveis.",
        "E... o tempo.",
        "Cinco séculos haviam passado.",
        "",
        "(Ele olha para o próprio peito — onde um enorme fragmento metálico está fundido à carne, no centro um núcleo circular pulsa em luz azulada, emitindo leves faíscas. O som distante de energia vibrando ecoa.)",
        "",
        "Verrin (baixo):",
        "Foi aí que percebi... algo dentro de mim ainda funcionava.",
        "Um núcleo. Um... coração que não era mais meu.",
        "",
        "(Ri sem humor.)",
        "Talvez o presente da fenda.",
        "Ou a marca do Eclipser.",
        "",
        "(O bracelete do piloto vibra e começa a projetar fragmentos holográficos — imagens distorcidas da superfície de Zenity: um planeta luminoso, com torres prateadas e símbolos da Coalizão das Constelações Livres refletindo nos céus.)",
        "",
        "Verrin (continuando):",
        "Fui direto pra Zenity.",
        "Pro salão central da Coalizão das Constelações Livres.",
        "Entrei, gritando pelos nomes deles — Rho, Lira, Thorn, Kira...",
        "Mas ninguém me reconhecia.",
        "Ninguém sequer sabia o que era o Esquadrão Havoc.",
        "",
        "(O holograma mostra Verrin mais jovem, confuso, cercado por guardas e figuras vestidas com mantos de prata e azul. O brasão da Ordem surge em destaque no teto — o símbolo da antiga Coalizão, agora corrompido.)",
        "",
        "Verrin (voz amarga):",
        "Tudo havia mudado.",
        "A Coalizão das Constelações Livres foi substituída pela Ordem — uma nova aliança que apagou tudo que veio antes.",
        "As pessoas olhavam pra mim como se eu fosse um delírio...",
        "Um velho soldado perdido no tempo.",
        "E quando contei o que vi...",
        "me chamaram de impostor.",
        "De louco.",
        "",
        "(O bracelete do piloto continua projetando fragmentos holográficos distorcidos — agora mostrando o rosto de Verrin em diferentes épocas, sempre sozinho, em mundos diferentes, repetindo o mesmo relato.)",
        "",
        "Verrin (ofegante):",
        "Passei séculos tentando contar o que aconteceu.",
        "De alguma forma, esse núcleo me mantém vivo...",
        "e nada que eu faça pode desligá-lo.",
        "Décadas viraram milênios... e eu ainda estava lá,",
        "preso entre o que sobrou do tempo e o que restou de mim.",
        "",
        "Cada vez que contava a história, diziam que era mentira.",
        "Que o núcleo no meu peito era só um adereço,",
        "um implante antigo pra manter a forma.",
        "",
        "(Ele se aproxima, trêmulo, o brilho do núcleo refletindo no rosto do piloto.)",
        "",
        "Verrin (gritando):",
        "Mas não é!",
        "NÃO É!",
        "Essa merda de metal!",
        "Este brilho maldito...",
        "é a prova do que aconteceu!",
        "Do que o Eclipser fez!",
        "Do que nós — o Esquadrão Havoc — fomos obrigados a fazer!",
        "",
        "(Ele para, ofegando. O silêncio pesa. A luz volta a pulsar lenta e triste. Verrin vira o rosto, a voz embargada.)",
        "",
        "Verrin (baixo):",
        "Mas você também não vai acreditar.",
        "Nenhum de vocês acredita.",
        "A Ordem ensinou o que devia ser lembrado...",
        "e apagou o resto.",
        "Então vai olhar pra mim, me ouvir...",
        "e pensar que sou só mais um velho preso em fantasmas de um tempo que nunca existiu.",
        "",
        "(O piloto fica em silêncio por alguns segundos. O bracelete continua emitindo ecos do passado. Ele olha para Verrin — não com dúvida, mas com curiosidade verdadeira.)",
        "",
        "Piloto (calmo, firme):",
        "Se tudo isso é verdade, Verrin...",
        "então me diga —",
        "onde o Eclipser está agora?",
    ],
};
