export const registro04 = {
    titulo: "Preocupação e Alívio - Chegada a Murfy",
    conteudo: [
        "Narração:",
        "O caminho até Murfy não constava nos mapas modernos.",
        "As coordenadas da mensagem corrompida o levaram por rotas antigas — trilhas de mineração e corredores fantasma esquecidos pela Ordem.",
        "",
        "[Som de interferência no painel, alarmes leves.]",
        "Piloto:",
        "“Desativar piloto automático. Rota manual... ênfase no campo de densidade estável.”",
        "",
        "Voz do Sistema:",
        "“Aviso: campo não reconhecido. Detecção de destroços e sinais de radiação residual muito elevados.”",
        "",
        "Piloto (murmurando):",
        "“É... parece o tipo de lugar que ninguém visita há muito tempo.”",
        "",
        "[Som de nave pousando, amortecedores hidráulicos, chiados de vapor.]",
        "",
        "Narração:",
        "Murfy ficava no que restava de uma antiga estação de abastecimento —",
        "uma estrutura curva, coberta de poeira estelar e letreiros quebrados piscando em vermelho.",
        "",
        "[Som de passos metálicos ecoando no corredor.]",
        "",
        "Narração:",
        "Fazia tempo que ele não sentia o chão sólido sob os pés.",
        "A sensação era estranha. Familiar, mas distante... como uma memória que insiste em sobreviver.",
        "",
        "[Som do comunicador abrindo — estática leve.]",
        "Colega (voz preocupada):",
        "“RS-07? Onde diabos você foi parar? O sistema mostra você fora do perímetro de Zenity há mais de três horas!”",
        "",
        "Piloto (tranquilo):",
        "“Só... seguindo uma coordenada antiga. Preciso verificar algo antes de voltar.”",
        "",
        "Colega (rindo de nervoso):",
        "“Verificar o quê, um buraco negro? A Ordem vai te arrancar as asas!”",
        "",
        "Piloto (sorrindo de leve):",
        "“Talvez valha a pena. Preciso ir...”",
        "",
        "Colega (nervoso):",
        "“Se tá maluc—!”",
        "[Som de canal encerrando abruptamente.]",
        "",
        "Narração:",
        "O comunicador silenciou.",
        "À frente, o corredor terminava em uma porta metálica escurecida, com um nome quase ilegível:",
        "MURFY.",
        "",
        "[Rangido da porta abrindo.]",
        "Um cheiro de óleo, ferrugem e destilado velho escapou pelo ambiente.",
        "",
        "Narração (voz baixa, envolvente):",
        "Um bar perdido nas bordas da galáxia...",
        "o tipo de lugar onde o passado vem para morrer.",
        "",
        "[Som ambiente: garrafas tilintando, vozes roucas, música distante em rádio antigo.]",
        "",
        "Narração (com leve eco):",
        "E foi ali... entre sombras e histórias esquecidas...",
        "que ele encontrou o homem que mudaria tudo.",
    ],
};