export const registro10 = {
    titulo: "A Ordem que Precede o Havoc",
    conteudo: [
        "(Verrin se aproxima, a voz agora rouca e grave, carregada de raiva contida.)",
        "",
        "Verrin:",
        "Porque não existe Ordem Estelar sem Havoc.",
        "Eles só mudaram o nome pra esconder o que restou.",
        "A Ordem — a nova Coalizão, se quiser chamar assim — nasceu do fracasso do Esquadrão.",
        "",
        "“Bem, se dizem que o Eclipser salvou a todos, então não foi um fracasso total.”",
        "",
        "(Ele ri de novo, mas o riso é curto, amargo. As luzes do bar piscam por um segundo, como se reagissem à lembrança.)",
        "",
        "Verrin (encarando o piloto):",
        "Então, da próxima vez que vestir esse uniforme e falar em “Glória da Ordem”...",
        "lembre-se:",
        "Ela foi construída em cima dos corpos daqueles que tentaram consertar o que o Eclipser destruiu.",
        "",
        "(O piloto desativa o holograma lentamente. O som se apaga. Por um instante, só se ouve o tilintar de uma garrafa sendo aberta ao fundo.)",
        "",
        "Piloto (baixo, sério):",
        "E o que aconteceu quando entraram nas regiões de Havoc?",
        "O que foram fazer lá? E como acabou?",
        "",
        "(Verrin fecha os olhos. Respira fundo. O ar parece pesar no ambiente.)",
        "",
        "Verrin (voz quase inaudível):",
        "Tudo.",
        "Tudo aconteceu.",
    ],
};
