export const registro17 = {
    titulo: "O Erro - Salto para o Desconhecido",
    conteudo: [
        "Narração:",
        "O piloto senta, prende o cinto. O bracelete se conecta com um clique sutil. O holograma do registro pisca: “MISSÃO REGISTRADA — SETOR HAVOC-9.”",
        "",
        "Piloto (baixinho, para si):",
        "Vamos ver se minha companheira ainda sabe voar.",
        "",
        "Narração:",
        "Ele ativa o canal de comunicação: um tom curto, limpo; a voz do Controle Zenity ecoa com formalidade serena.",
        "",
        "Piloto — Canal Aberto (RS-07):",
        "“Controle Zenity, aqui é o piloto RS-07 solicitando autorização de saída para missão operacional — destino: Setor Havoc-9. Status: tripulante único, contingência mínima confirmada.”",
        "",
        "Controle Zenity (voz calma, com timbre institucional):",
        "“Aguarde... Unidade RS-07, confirmação recebida. Missão HAVOC-9 classificada como Prioridade Máxima. Prazo operacional: 14 dias.",
        "Você foi autorizado a partir pela Ordem Estelar de Reconhecimento.",
        "Relembramos: manter enlace com estação sempre que possível.",
        "Caso exceda o tempo de missão e não retorne em 5 dias, você será dado como desaparecido e devido ao risco da missão, você estará por conta própria.",
        "Boa sorte, RS-07.”",
        "",
        "Piloto (um leve sorriso, meio irônico):",
        "“Copiado, Controle. Link ativo. Vou manter contato a cada 3 horas.”",
        "",
        "Controle Zenity:",
        "“Muito bem piloto! Registro de missão ativo. Boa viagem, RS-07. Fim do canal.”",
        "",
        "Narração:",
        "O canal fecha com um click. O piloto solta o ar, as luzes internas mudam de tom; o painel aquece como um animal prestes a correr.",
        "",
        "Sistema de Bordo (voz metálica):",
        "[✔] Energia estabilizada.",
        "[✔] Propulsor de salto: em espera.",
        "[✔] Rotas de voo: calculadas.",
        "",
        "Narração:",
        "O piloto observa o reflexo no vidro do cockpit — a cidade de Zenity atrás dele, brilhando com promessas e rostos que ele carrega consigo.",
        "",
        "Piloto (voz firme, olhando para os amigos pela última vez):",
        "Partindo… para o Setor Havoc-9.",
        "",
        "Narração:",
        "A nave já está fora da atmosfera. O painel exibe rotas brilhando em azul, luzes refletindo no capacete do piloto. O espaço se abre — sereno demais.",
        "",
        "Sistema de Bordo:",
        "[✔] Nave fora de zona planetária.",
        "[✔] Propulsor de salto: pronto.",
        "Iniciando pré-carga…",
        "",
        "Narração:",
        "O piloto empurra lentamente a manete de fluxo. O som grave cresce, como um coração mecânico acelerando.",
        "",
        "Piloto (murmurando para si):",
        "Só um salto limpo… nada fora do normal.",
        "",
        "Narração:",
        "O bracelete vibra. Uma notificação surge.",
        "",
        "ZACK VATULY — 1 mensagem nova",
        "O piloto abre. Um vídeo curto.",
        "",
        "Zack (vídeo, rindo):",
        "“Se você morrer… eu fico com seus lanches escondidos no armário da nave, valeu?",
        "Vai logo antes que eu suba aí e desligue tudo de novo!”",
        "",
        "Narração:",
        "O piloto sorri — mas não responde. Fecha o vídeo.",
        "No mesmo instante, outra notificação aparece.",
        "",
        "DAVE HOLTFORD — transmissão urgente",
        "",
        "Piloto (atende):",
        "Dave? Tô entrando na fase de salto, fala rápido.",
        "",
        "Dave (voz com estática do hangar):",
        "“RS-07… escuta. Eu revisei os módulos depois que você saiu.",
        "Os motores ainda estão baixando os dados do painel. Eles NÃO devem ser sobrecarregados no primeiro salto.",
        "Repito: NÃO sobrecarrega os motores — ou a curva temporal pode—”",
        "",
        "Narração:",
        "A transmissão é engolida por ruído.",
        "",
        "Piloto (tenso):",
        "Dave…? Repete isso. Repete!",
        "",
        "Narração:",
        "O sinal corta. Som seco. O piloto olha para o painel, onde os motores já estão se alinhando.",
        "",
        "Sistema de Bordo:",
        "[⚠] Fluxo excedendo limite recomendado.",
        "[⚠] Curva estabilizadora não sincronizada.",
        "Recalibrar?",
        "",
        "Piloto (engolindo seco):",
        "Merda… eu já passei do ponto de retorno. Porra, porque não me falou isso antes que eu entrasse na nave, Dave...",
        "",
        "Narração:",
        "Ele olha para a fotografia presa na lateral — ele, Lyra, Zack e Dave. A mão aperta o comando.",
        "",
        "Piloto:",
        "Segura firme, companheira. Vamos juntas.",
        "",
        "Sistema de Bordo:",
        "Iniciando sequência de dobra automática em 3… 2… 2.5... 7.2594654...",
        "",
        "Narração:",
        "Um clarão azul rasga o cockpit. Linhas de luz distorcem como cordas sendo puxadas. O painel começa a piscar.",
        "",
        "Sistema de Bordo (voz distorcendo):",
        "[⚠] Erro de vetorização.",
        "[⚠] Falha de calibração temporal.",
        "[⚠] Sincronização comprometida.",
        "[⚠] Correção manual requer—",
        "",
        "Narração:",
        "A voz corta. O tempo treme. Fragmentos do visor mostram datas saltando aleatoriamente: “+07 dias”, “-03 horas”, “+62 dias”, “+00 anos / +02 meses”.",
        "",
        "Piloto (gritando contra a vibração):",
        "NÃO, NÃO, NÃO—",
        "Campo de dobra invertido?!",
        "Isso não é possível!",
        "",
        "Narração:",
        "A nave gira dentro de um túnel de luz quebrada. Tudo fica branco — depois cinza — depois silêncio absoluto.",
        "",
        "Narração:",
        "A tela volta. Devagar. Como se o mundo estivesse sendo redesenhado ao redor da nave.",
        "A nave flutua em um mar escuro de partículas cintilantes.",
        "Relâmpagos azuis atravessam os destroços ao redor.",
        "O espaço parece... rasgado.",
        "",
        "Sistema de Bordo (voz baixa, quase falhando):",
        "[⚠] Destino desconhecido.",
        "[⚠] Assinatura espacial incompatível com arquivos de navegação.",
        "[⚠] Anomalia detectada em: FETHURI.",
        "",
        "Narração:",
        "O piloto acorda depois de ficar inconsciente no salto. Ele recobra a consciência assustado por nunca ter ouvido a palavra FETHURI no sistema.",
        "",
        "Piloto (olhando para fora, assustado):",
        "Fethuri…?",
        "O que diabos é esse lugar…?",
        "",
        "Narração:",
        "O radar dispara um som grave — um único pulso, como um batimento cardíaco. Uma sombra passa rápido demais para ter forma.",
        "O piloto ativa as luzes externas.",
        "O brilho revela rachaduras no próprio espaço, como fraturas emitindo luz interna.",
        "",
        "Piloto (sussurro):",
        "Porra Dave, onde que eu estou agora? Espera… durante o salto as coordenadas foram alteradas e não tem nada a ver com o motor!",
        "Alguma coisa me puxou pra cá.",
        "",
        "Narração:",
        "A tela treme. O símbolo do Eclipser aparece no painel por menos de meio segundo — distorcido, como um glitch — antes de desaparecer.",
        "O som vai diminuindo… diminuindo… até ficar só o silêncio estranho de Fethuri.",
        "",
        "“SEÇÃO 02 – NAS SOMBRAS DE HAVOC”",
        "Missão Ativa: Reconfigurar o sistema de navegação e identificar a origem da Anomalia FETHURI.",
    ],
};
