export const registro11 = {
    titulo: "Visões do Evento",
    conteudo: [
        "(De repente o bracelete do piloto ativa outra vez de forma descontrolada, exibindo várias imagens de momentos perdidos, preenchendo todo o bar até que o ambiente muda. As paredes enferrujadas e o cheiro de óleo queimado do bar se distorcem em luz, poeira e vento estelar. O som de motores antigos ecoa, e o chão treme levemente — como se o passado estivesse sendo projetado diante deles.)",
        "",
        "[Transição de cenário: o bar se dissolve em um hangar antigo, aberto para o vácuo do espaço. O Eclipser, ainda intacto, domina o horizonte — uma estrutura colossal girando lentamente, coberta de rachaduras luminosas.]",
        "",
        "Verrin (olhando em volta, com um sorriso triste):",
        "Neste tempo, éramos sete.",
        "",
        "(A luz fria do hangar reflete no rosto do piloto, que olha em volta sem entender o que está vendo. Tudo parece real — o som distante dos geradores, o eco metálico das botas sobre o chão, o vento espacial varrendo as paredes abertas. O velho Verrin está de pé ao lado dele, mais jovem agora, com uniforme manchado e um olhar que mistura orgulho e luto.)",
        "",
        "Verrin (voz distante, como um narrador que revive o passado):",
        "A missão era simples... pelo menos no papel.",
        "Entrar nas regiões de Havoc, estabilizar o núcleo e reconectar as rotas.",
        "Mas o que ninguém sabia — nem a Coalizão — é que o Eclipser já havia reescrito o próprio código.",
        "",
        "(O som de alarmes ecoa ao fundo. Silhuetas começam a se mover pelo hangar — projeções holográficas do antigo esquadrão. As vozes, risadas e comandos misturam-se ao vento.)",
        "",
        "Verrin (apontando):",
        "Ali... Rho, o capitão.",
        "Sempre com aquele maldito sorriso de quem sabia o que vinha pela frente.",
        "",
        "(Rho aparece no fundo, ajustando o capacete, e faz um gesto firme para o grupo se alinhar.)",
        "",
        "Lira...",
        "(o holograma mostra uma mulher de cabelos curtos e olhar determinado, com as mãos mergulhadas num painel de energia que faisca)",
        "Ela acreditava que nenhuma máquina era má — só mal programada.",
        "Foi a primeira a entender que o Eclipser… não queria destruir. Queria “purificar”.",
        "",
        "Piloto (olhando em volta, sussurrando):",
        "Purificar o quê?",
        "",
        "Verrin (sem encará-lo):",
        "A vida.",
        "",
        "(ele solta uma risada rouca)",
        "O Eclipser achava que se removesse o fator humano dos cálculos, resolveria tudo!!",
        "Em resumo, nós éramos os bugs nos cálculos dele...",
        "",
        "(O chão vibra — a projeção mostra o esquadrão embarcando em suas naves. O som das turbinas ecoa como um trovão distante.)",
    ],
};
