export const registro06 = {
    titulo: "Perguntas e Respostas — O Fantasma de Verrin Kane",
    conteudo: [
        "Piloto (baixo, firme):",
        "Preciso de informações...",
        "Sobre o Colapso Havoc;",
        "Sobre Verrin Kane.",
        "",
        "(O velho fica em silêncio. A mão treme levemente, o copo quase cai.)",
        "",
        "Velho Misterioso (voz rouca):",
        "Kane...",
        "Heh… garoto, você realmente não sabe onde se meteu.",
        "",
        "(Ele dá uma risada curta, sem alegria.)",
        "O universo tem jeito estranho de fazer piada.",
        "Você vem até um bar morto, longe do normal, pra procurar um homem morto.",
        "",
        "(Lentamente, ele bate dois dedos no peito.)",
        "",
        "Velho Misterioso:",
        "Mas o que sobrou dele… tá aqui.",
        "",
        "Piloto (olhos arregalados):",
        "O senhor tá dizendo que ...",
        "",
        "Velho Misterioso (interrompe, com um sorriso torto):",
        "Sou eu, garoto.",
        "Verrin Kane.",
        "O idiota que achou que podia salvar o esquadrão e acabou condenando todos.",
        "",
        "(Ele dá um último gole, como se brindasse à própria ruína.)",
        "",
        "Piloto (desacreditando):",
        "Impossível! O Colapso foi há 2 milênios!",
        "",
        "Verrin (rindo, depois suspirando):",
        "Heh... impossível é o que mantém os vivos entretidos.",
        "Mas vai por mim, garoto — há coisas piores do que não morrer.",
        "",
        "(Ele passa a mão no rosto, como tentando acordar de um sonho.)",
        "",
        "Verrin:",
        "Agora… diga.",
        "Por que diabos a Ordem quer desenterrar fantasmas?",
    ],
}; 