export const registro18 = {
    titulo: "Despertar em Fethuri - Explorando os Registros",
    conteudo: [
        "Narração:",
        "[REGISTROS DA NAVE PÓS SALTO]",
        "A nave paira imóvel no coração distorcido de Fethuri. Luzes fracas piscam pelo cockpit enquanto o piloto desperta lentamente, a cabeça latejando.",
        "",
        "Piloto:",
        "O que… aconteceu?",
        "Sistema… o que houve durante o salto?",
        "",
        "Sistema de Bordo:",
        "[⚠] Erros críticos registrados.",
        "[⚠] Múltiplos alertas pendentes.",
        "[⚠] Recomendação: revisar painel de avisos.",
        "",
        "Piloto:",
        "Dois… dois meses inconsciente?",
        "Não… não pode ser…",
        "",
        "Narração:",
        "Ele fecha dezenas de alertas vermelhos deslizando o dedo pelo holograma.",
        "",
        "Piloto:",
        "Aviso… ignorar.",
        "Aviso crítico… também ignorar.",
        "Você também… e você…",
        "…e você que está piscando desde o salto.",
        "Chega de alarme gritando comigo.",
        "",
        "Narração:",
        "Os alertas se apagam, mas um ícone pisca: 142 mensagens não lidas.",
        "",
        "Piloto:",
        "Cento e quarenta e duas…?",
        "",
        "Narração:",
        "O piloto abre as mensagens. O HUD exibe automaticamente as últimas comunicações recebidas pelo grupo, pelo sistema e pela Ordem Estelar.",
        "Ele lê tudo — cada registro frenético, cada aviso, cada tentativa dos amigos de alcançá-lo durante o período em que esteve perdido.",
        "",
        "Narração:",
        "Após revisar todo o histórico de comunicações, o piloto fecha o painel.",
        "Ele está sozinho.",
        "",
        "Piloto:",
        "Certo… certo. Se ninguém vem… eu vou sair daqui sozinho.",
        "",
        "Narração:",
        "Ele abre o painel principal. Vários módulos piscam em vermelho, outros simplesmente não respondem.",
        "",
        "Sistema de Bordo:",
        "[SISTEMA DE ENERGIA: ONLINE]",
        "[SENSORIAL PRIMÁRIO: ONLINE]",
        "[SENSOR DE PROXIMIDADE: CALIBRAÇÃO PENDENTE]",
        "[SENSOR DE ANOMALIA: RUÍDO 87%]",
        "[MOTORES: OPERANTES]",
        "[MOTOR PRIMÁRIO: POTÊNCIA REDUZIDA]",
        "[MOTOR SECUNDÁRIO: POTÊNCIA REDUZIDA]",
        "[PROPULSOR DE SALTO: DANIFICADO]",
        "[SUPORTE DE VIDA: ONLINE – MODO ECONÔMICO]",
        "[ATMOSFERA INTERNA: 72%]",
        "[COMUNICAÇÃO: OFFLINE]",
        "[CANAL DE EMERGÊNCIA: NÃO ENCONTRADO]",
        "[RECEPTOR DE LONGA DISTÂNCIA: REINICIALIZAÇÃO FALHA]",
        "[PILOTAGEM ASSISTIDA: DESATIVADA]",
        "[ORIENTAÇÃO INERCIAL: ERRO]",
        "[GIROSCÓPIO: INVERTIDO – EIXO Y NEGATIVO]",
        "[HUD TÁTICO: ONLINE]",
        "[ESCUDO: 12% – INOPERANTE]",
        "[CASCO: DANO CRÍTICO – COMPARTIMENTOS 3, 4, 7 EXPOSTOS]",
        "[SISTEMA DE NAVEGAÇÃO: ROTA PERDIDA]",
        "[MAPA ESTELAR: CORROMPIDO – 63% DOS SETORES INACESSÍVEIS]",
        "[IA AUXILIAR MK-IV: MODO DE ACESSO A REGISTROS]",
        "[...]",
        "[STATUS GERAL: SISTEMA FUNCIONANDO EM 22% DA SUA CAPACIDADE]",
        "",
        "Piloto:",
        "Ótimo. Perfeito. Agora vou ter que dar uma de Dave e consertar a nave.",
        "Isso vai ser… divertidíssimo.",
        "",
        "Sistema de Bordo:",
        "[TENTANDO SINCRONIZAR ORIENTAÇÃO…]",
        "[✖ FALHA]",
        "[Causa provável: Interferência externa]",
        "",
        "Piloto:",
        "OK…",
        "Se até o espaço tá torto aqui…",
        "Eu vou ter que voar… torto.",
        "",
        "Narração:",
        "Ele desativa o travamento da cabine. As luzes externas se acendem, revelando a escuridão viva de Fethuri girando em padrões impossíveis.",
        "",
        "Piloto:",
        "Vamos lá, Sirius…",
        "Mostra pra mim onde é ‘cima’.",
        "",
        "Narração:",
        "A nave vibra como se despertasse. Os estabilizadores respondem com dificuldade, mas respondem.",
        "",
        "[INICIANDO MODO DE CONTROLE MANUAL COM GIROSCÓPIO INSTÁVEL]",
        "[PREPARANDO SISTEMA PARA PRIMEIRO MOVIMENTO]",
        "",
        "Piloto:",
        "É agora…",
        "",
        "Narração:",
        "O prólogo termina — o jogo começa.",
        "",
        "Letreiro:",
        "“MISSÃO ATUALIZADA — SETOR FETHURI”",
        "Submissão paralela desbloqueada: ‘Descobrindo um novo Setor’.",
    ],
};
