export const registro06 = {
    titulo: "Perguntas e Respostas — O Fantasma de Verrin Kane",
    conteudo: [
        "Piloto (baixo, firme):",
        "Agora que eu te entreguei algo, não vou sair daqui sem me entregar algo de volta.",
        "Preciso de informações...",
        "Sobre o Colapso Havoc;",
        "Sobre Verrin Kane.",
        "",
        "Narração:",
        "O velho fica em silêncio. A mão treme levemente, o copo quase cai.",
        "",
        "Velho Misterioso (voz rouca):",
        "Kane...",
        "Heh… garoto, você realmente não sabe onde se meteu.",
        "",
        "Narração:",
        "Ele dá uma risada curta, sem alegria.",
        "",
        "Velho Misterioso (voz rouca):",
        "O universo tem jeito estranho de fazer piada.",
        "Você vem até um bar morto, longe do normal, pra procurar um homem morto.",
        "",
        "Narração:",
        "Lentamente, ele bate dois dedos no peito.",
        "",
        "Velho Misterioso:",
        "Mas o que sobrou dele… tá aqui.",
        "",
        "Piloto (olhos arregalados):",
        "O senhor tá dizendo que ...",
        "",
        "Velho Misterioso (interrompe, com um sorriso torto):",
        "Sou eu, garoto.",
        "Verrin Kane.",
        "O idiota que achou que podia salvar o universo e acabou aqui nesse bar",
        "",
        "Narração:",
        "Ele dá um último gole, como se brindasse à própria ruína.",
        "",
        "Piloto (desacreditando):",
        "Impossível! O Colapso foi há 2 milênios!",
        "",
        "Verrin (rindo, depois suspirando):",
        "Heh... impossível é o que mantém os vivos entretidos.",
        "Mas vai por mim, garoto — há coisas piores do que não morrer.",
        "",
        "Narração:",
        "Ele passa a mão no rosto, como tentando acordar de um sonho.",
        "",
        "Verrin:",
        "Agora… diga.",
        "Por que diabos a Ordem quer desenterrar fantasmas?",
    ],
}; 