export const registro02 = {
    titulo: "Missão e Estudo – Primeiras Pistas Sobre Havoc",
    conteudo: [
        "[Som de portas automáticas abrindo, um breve sopro de ar filtrado.]",
        "Narração:",
        "Depois de reportar sua chegada, alugou um pequeno quarto nas margens da estação principal.",
        "Pequeno, silencioso — uma janela sem vista, só o brilho distante das rotas orbitais.",
        "Ali, enfim, pôde respirar.",
        "",
        "[Som de cadeira deslizando, o zumbido de um projetor holográfico sendo ativado.]",
        "Voz automatizada:",
        `"Mensagem recebida da Organização Estelar: `,
        `Operação: Expedição Setor Havoc`,
        `Objetivo: localizar e extrair módulo ‘núcleo de dobra’ — prioridade classe Ômega.`,
        `Janela de partida: 48 horas a partir deste aviso.`,
        `Duração estimada: 7–14 dias, variável conforme instabilidade gravitacional.`,
        `Risco: crítico — zona fora do mapa de salto registrado.`,
        `Remuneração: 120.000 créditos Z — com bônus adicional mediante integridade total do núcleo.`,
        `Preparativos obrigatórios: calibração de matriz de dobra, isolamento de pulso, contenção magnética e protocolo offline ativo.`,
        `Autorização: Nível expedicionário — Ordem Estelar de Reconhecimento.`,
        `Confirme aceitação e registre assinatura de missão."`,
        "",
        "Piloto (voz baixa, pensativa):",
        `"Setor Havoc... núcleo de dobra..."`,
        "(pausa)",
        `"Sempre mandam a gente pra consertar o que já devia ter ficado morto."`,
        "(ele tira o comunicador do pulso e o coloca sobre a mesa)",
        `"Três dias... vou fingir que é o bastante."`,
        "(suspira, deita-se)",
        `"Amanhã eu começo a entender o que diabos a Ordem quer achar lá fora..."`,
        "[Som do bracelete desligando. Tela escurece lentamente.]",
        "",
        "Narração:",
        "No dia seguinte, ele decidiu usar o tempo livre pra entender melhor o que o aguardava.",
        "A missão mencionava o Setor Havoc — um nome que ecoava nos arquivos mais antigos, e nos silêncios mais pesados da história galáctica.",
        "Enquanto pensava, se dirigiu ao Observatório Central, lugar que armazenava todo o conhecimento da humanidade...",
        "",
        "Piloto (murmurando enquanto lê):",
        `"Colapso Havoc... evento de interferência gravitacional... falha de controle... perda total de comunicação com a frota..."`,
        "[Som de telas digitais passando rapidamente, acompanhadas de uma leve trilha de tensão crescente.]",
        "",
        "Narração:",
        "Quanto mais ele lia, mais sentia que algo não batia.",
        "Tudo soava... limpo demais. Controlado demais.",
        "Nenhum registro que explicasse direito a história, apenas relatórios da Ordem — todos descrevendo o mesmo final conveniente:",
        `"O Eclipser estabilizou o colapso.`,
        `Seis pilotos deram suas vidas pela restauração da galáxia."`,
        "",
        "Piloto (suspira):",
        `"Seis pilotos... e nenhum nome. Nem uma assinatura. Só números de registro..."`,
    ],
};